### ISSUE TITLE
PHP Warning

### ISSUE THREAD

**Issue by herrrilke** [vonheldenundgestalten/contao-boxes#2]
... und diese warnung erhalte ich bei migrate:

```powershell
PHP Warning:  Undefined array key "deleteConfirm" in /mnt/web215/var/cache/prod/contao/dca/tl_boxen.php on line 37

``` 

VG karsten

**Comment by kimleta** [comment]
Hello @herrrilke 

I found what error was and I fixed it in a code, but we will wait for some time to see if something else broke so we can fix it and then we will publish it. 

Error was exact as this one in this Contao discussion and solution was same.
[https://community.contao.org/de/showthread.php?80218-PHP-8-bringt-Warnings](https://community.contao.org/de/showthread.php?80218-PHP-8-bringt-Warnings)

In meanwhile I recommend you disabling PHP warnings because PHP 8 is aggressive with them.

**Comment by markusmilkereit** [comment]
Turning down the error_reporting should be done on "Hosting" level, but Strato does not offer that setting - so we used the **config.yml** to overwrite the basic Contao setting on projects hosted at Strato:
```
contao:
    error_level:          0
```
